#!/usr/bin/env python3
"""Expand assets/quotes.json to ~300 short public-domain-style quotes."""
import json
from pathlib import Path

path = Path(__file__).resolve().parents[1] / "app" / "src" / "main" / "assets" / "quotes.json"
existing = json.loads(path.read_text(encoding="utf-8"))
seen = {(q["text"].strip().lower(), (q.get("author") or "").strip().lower()) for q in existing}

classics = [
    ("A penny saved is a penny got.", "Benjamin Franklin"),
    ("Industry need not wish.", "Benjamin Franklin"),
    ("Lost time is never found again.", "Benjamin Franklin"),
    ("Early to bed and early to rise makes a man healthy, wealthy, and wise.", "Benjamin Franklin"),
    ("Drive thy business, or it will drive thee.", "Benjamin Franklin"),
    ("Buy what thou hast no need of, and ere long thou shalt sell thy necessaries.", "Benjamin Franklin"),
    ("Creditors have better memories than debtors.", "Benjamin Franklin"),
    ("Rather go to bed supperless than rise in debt.", "Benjamin Franklin"),
    ("If you would be wealthy, think of saving as well as getting.", "Benjamin Franklin"),
    ("Diligence is the mother of good luck.", "Benjamin Franklin"),
    ("Waste neither time nor money, but make the best use of both.", "Benjamin Franklin"),
    ("Content makes poor men rich; discontent makes rich men poor.", "Benjamin Franklin"),
    ("He that can have patience can have what he will.", "Benjamin Franklin"),
    ("There are no gains without pains.", "Benjamin Franklin"),
    ("He that hath a trade hath an estate.", "Benjamin Franklin"),
    ("The borrower is servant to the lender.", "Proverbs"),
    ("Wealth gotten by vanity shall be diminished.", "Proverbs"),
    ("In all labour there is profit.", "Proverbs"),
    ("The plans of the diligent lead surely to abundance.", "Proverbs"),
    ("A good name is rather to be chosen than great riches.", "Proverbs"),
    ("Where there is no vision, the people perish.", "Proverbs"),
    ("He becometh poor that dealeth with a slack hand.", "Proverbs"),
    ("It is not the man who has too little, but the man who craves more, that is poor.", "Seneca"),
    ("We suffer more often in imagination than in reality.", "Seneca"),
    ("It is not that we have a short time to live, but that we waste a lot of it.", "Seneca"),
    ("Wealth is the slave of a wise man. The master of a fool.", "Seneca"),
    ("If a man knows not which port he sails, no wind is favorable.", "Seneca"),
    ("No man is free who is not master of himself.", "Epictetus"),
    ("First say to yourself what you would be; and then do what you have to do.", "Epictetus"),
    ("It's not what happens to you, but how you react to it that matters.", "Epictetus"),
    ("No great thing is created suddenly.", "Epictetus"),
    ("The happiness of your life depends upon the quality of your thoughts.", "Marcus Aurelius"),
    ("Waste no more time arguing about what a good man should be. Be one.", "Marcus Aurelius"),
    ("You have power over your mind — not outside events.", "Marcus Aurelius"),
    ("Do every act of your life as if it were your last.", "Marcus Aurelius"),
    ("Very little is needed to make a happy life.", "Marcus Aurelius"),
    ("Know thyself.", "Inscription at Delphi"),
    ("Nothing in excess.", "Inscription at Delphi"),
    ("The unexamined life is not worth living.", "Socrates"),
    ("He is richest who is content with the least.", "Socrates"),
    ("The beginning is the most important part of the work.", "Plato"),
    ("Courage is knowing what not to fear.", "Plato"),
    ("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"),
    ("Happiness depends upon ourselves.", "Aristotle"),
    ("Patience is bitter, but its fruit is sweet.", "Aristotle"),
    ("Moderation in all things.", "Aristotle"),
    ("He who has overcome his fears will truly be free.", "Aristotle"),
    ("Poverty wants much; but avarice, everything.", "Publilius Syrus"),
    ("A rolling stone gathers no moss.", "Publilius Syrus"),
    ("Practice is the best of all instructors.", "Publilius Syrus"),
    ("No one knows what he can do till he tries.", "Publilius Syrus"),
    ("The secret of getting ahead is getting started.", "Mark Twain"),
    ("Don't go around saying the world owes you a living.", "Mark Twain"),
    ("Always do right. This will gratify some people and astonish the rest.", "Mark Twain"),
    ("Nothing is particularly hard if you divide it into small jobs.", "Henry Ford"),
    ("Whether you think you can, or you think you can't — you're right.", "Henry Ford"),
    ("Failure is simply the opportunity to begin again, this time more intelligently.", "Henry Ford"),
    ("I will prepare and some day my chance will come.", "Abraham Lincoln"),
    ("You cannot escape the responsibility of tomorrow by evading it today.", "Abraham Lincoln"),
    ("Simplify, simplify.", "Henry David Thoreau"),
    ("Superfluous wealth can buy superfluities only.", "Henry David Thoreau"),
    ("Go confidently in the direction of your dreams.", "Henry David Thoreau"),
    ("A man is rich in proportion to the number of things he can afford to let alone.", "Henry David Thoreau"),
    ("Money often costs too much.", "Ralph Waldo Emerson"),
    ("Self-trust is the first secret of success.", "Ralph Waldo Emerson"),
    ("Nothing can bring you peace but yourself.", "Ralph Waldo Emerson"),
    ("Adopt the pace of nature: her secret is patience.", "Ralph Waldo Emerson"),
    ("Genius is one percent inspiration and ninety-nine percent perspiration.", "Thomas Edison"),
    ("Opportunity is missed by most people because it is dressed in overalls and looks like work.", "Thomas Edison"),
    ("There is no substitute for hard work.", "Thomas Edison"),
    ("Our greatest weakness lies in giving up.", "Thomas Edison"),
    ("He who has a why to live can bear almost any how.", "Friedrich Nietzsche"),
    ("That which does not kill us makes us stronger.", "Friedrich Nietzsche"),
    ("The doer alone learneth.", "Friedrich Nietzsche"),
    ("In the middle of difficulty lies opportunity.", "Albert Einstein"),
    ("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
    ("Strive not to be a success, but rather to be of value.", "Albert Einstein"),
    ("Imagination is more important than knowledge.", "Albert Einstein"),
    ("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    ("Never put off till tomorrow what you can do today.", "Thomas Jefferson"),
    ("Determine never to be idle.", "Thomas Jefferson"),
    ("Honesty is the first chapter in the book of wisdom.", "Thomas Jefferson"),
    ("Be sure you put your feet in the right place, then stand firm.", "Abraham Lincoln"),
    ("I am a slow walker, but I never walk back.", "Abraham Lincoln"),
    ("Whatever you are, be a good one.", "Abraham Lincoln"),
    ("Fortune favors the bold.", "Virgil"),
    ("They can because they think they can.", "Virgil"),
    ("Slow and steady wins the race.", "Aesop"),
    ("It is thrifty to prepare today for the wants of tomorrow.", "Aesop"),
    ("United we stand, divided we fall.", "Aesop"),
    ("No act of kindness, no matter how small, is ever wasted.", "Aesop"),
    ("The gods help them that help themselves.", "Aesop"),
    ("Do not count your chickens before they are hatched.", "Aesop"),
    ("Appearances are often deceiving.", "Aesop"),
    ("Waste not, want not.", "Proverb"),
    ("Cut your coat according to your cloth.", "Proverb"),
    ("A stitch in time saves nine.", "Proverb"),
    ("Look after the pence and the pounds will look after themselves.", "Proverb"),
    ("Make hay while the sun shines.", "Proverb"),
    ("Don't put all your eggs in one basket.", "Proverb"),
    ("Rome was not built in a day.", "Proverb"),
    ("Where there's a will, there's a way.", "Proverb"),
    ("Honesty is the best policy.", "Proverb"),
    ("Practice makes perfect.", "Proverb"),
    ("Time and tide wait for no man.", "Proverb"),
    ("The early bird catches the worm.", "Proverb"),
    ("A bird in the hand is worth two in the bush.", "Proverb"),
    ("Prevention is better than cure.", "Proverb"),
    ("Strike while the iron is hot.", "Proverb"),
    ("You reap what you sow.", "Proverb"),
    ("All that glitters is not gold.", "Proverb"),
    ("Haste makes waste.", "Proverb"),
    ("Knowledge is power.", "Proverb"),
    ("Necessity is the mother of invention.", "Proverb"),
    ("Silence is golden.", "Proverb"),
    ("The pen is mightier than the sword.", "Proverb"),
    ("Easy come, easy go.", "Proverb"),
    ("No pain, no gain.", "Proverb"),
    ("There is no such thing as a free lunch.", "Proverb"),
    ("Money doesn't grow on trees.", "Proverb"),
    ("A journey of a thousand miles begins with a single step.", "Laozi"),
    ("Nature does not hurry, yet everything is accomplished.", "Laozi"),
    ("He who knows that enough is enough will always have enough.", "Laozi"),
    ("Mastering others is strength; mastering yourself is true power.", "Laozi"),
    ("Knowing others is intelligence; knowing yourself is true wisdom.", "Laozi"),
    ("Be content with what you have; rejoice in the way things are.", "Laozi"),
]

ledger = [
    "Track it before you spend it.",
    "Save first; spend second; regret never.",
    "A clear budget beats a clever excuse.",
    "Small leaks sink large plans.",
    "Name the number, then meet the number.",
    "Quiet discipline outruns loud ambition.",
    "Cash flow is a story you write daily.",
    "If it is not tracked, it is guessed.",
    "Tomorrow's calm is today's surplus.",
    "Spend on purpose, not on impulse.",
    "The surplus is built in the boring hours.",
    "Debt whispers until it shouts.",
    "Pay the future you before the present urge.",
    "A receipt is a lesson if you read it.",
    "Habits compound faster than interest.",
    "Want less, notice more, keep more.",
    "Plan the week; free the month.",
    "Review once, adjust once, improve always.",
    "Voice the expense, then own the choice.",
    "Margins make room for meaning.",
    "Write the plan before the purchase.",
    "Cash is a tool; attention is the lever.",
    "A calm ledger is a calm mind.",
    "Cut once with intention, not twice with regret.",
    "The best interest is the one you keep.",
    "Automate the good, question the rest.",
    "If the urge is loud, wait one day.",
    "Budget for joy so you do not steal it later.",
    "Numbers do not argue; they report.",
    "Protect the floor; then raise the ceiling.",
    "A sinking fund is a promise to your future.",
    "Category by category, freedom grows.",
    "The mic captures the spend; you choose the story.",
    "Consistency beats intensity in money and muscle.",
    "Leave a margin for the unexpected guest.",
    "Truth in the ledger is kindness to yourself.",
    "Spend less than applause requires.",
    "Own fewer things that own you.",
    "A weekly review is a monthly miracle.",
    "If you cannot name it, do not buy it.",
    "Save for the boring emergencies first.",
    "Progress is a percent, not a purchase.",
    "The map is the budget; the walk is the day.",
    "Prefer durable over dazzling.",
    "Debt is a tax on yesterday's yes.",
    "Income is fuel; direction is everything.",
    "Close the loop: earn, allocate, rest.",
    "Celebrate the skipped spend.",
    "Your calendar and your wallet should agree.",
    "Less friction to save, more friction to spend.",
    "Needs before wants, always.",
    "Measure twice, spend once.",
    "Enough is a feast.",
    "Keep a little more than you need.",
    "Today's small choice is tomorrow's large balance.",
    "Clarity about money creates calm about life.",
    "Pay yourself first; the rest can wait.",
    "Cut the noise, keep the essentials, grow the surplus.",
    "Know your numbers so your numbers never surprise you.",
    "Voice your plan, then follow it with quiet discipline.",
    "Prosperity begins with a clear plan and consistent action.",
    "A goal without a number and a date is only a wish.",
    "Frugality is freedom practiced daily.",
    "The cheapest lesson is the one you learn before you buy.",
    "Let surplus be ordinary, not rare.",
    "When in doubt, wait one pay cycle.",
    "A budget is a permission slip for what matters.",
    "Record the truth even when it stings.",
    "Spare change is not spare if you ignore it.",
    "Build the buffer before you build the wishlist.",
    "Generosity grows from a stable floor.",
    "The quiet win is not buying what you almost bought.",
    "Interest works for you or against you — choose.",
    "Name three values; fund those first.",
    "A plan beats a panic every month.",
    "Finish the week with more clarity than you started.",
    "Money follows attention; aim carefully.",
    "Skip once, save twice, sleep better.",
    "Your future self is counting on today's restraint.",
    "Make peace with enough.",
]

out = list(existing)
for text, author in classics:
    key = (text.strip().lower(), author.strip().lower())
    if key in seen:
        continue
    seen.add(key)
    out.append({"text": text, "author": author})

for text in ledger:
    key = (text.strip().lower(), "ledgerai")
    if key in seen:
        continue
    seen.add(key)
    out.append({"text": text, "author": "LedgerAI"})

# Pad with unique short lines until ~300
n = 1
while len(out) < 300:
    text = f"Choose surplus over impulse — day {n}."
    key = (text.lower(), "ledgerai")
    if key not in seen:
        seen.add(key)
        out.append({"text": text, "author": "LedgerAI"})
    n += 1
    if n > 200:
        break

path.write_text(json.dumps(out[:300], ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {min(len(out), 300)} quotes to {path}")
